//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyXeMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Spatial;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class DangKyXeMay
    {
        [Required]
        [StringLength(200)]
        [Display(Name = "Mã đăng ký")]
        public int ToKhaiDK_ID { get; set; }

        [StringLength(200)]
        [Display(Name="Mã người dùng")]
        public int registerID { get; set; }


        [StringLength(250)]
        [Display(Name = "Tên người (ĐSH)")]
        public string co_ownerName { get; set; }

        [StringLength(200)]
        [Display(Name = "CMND (ĐSH)")]
        public string co_ownerCMND { get; set; }

        [StringLength(200)]
        [Display(Name = "Ngày Cấp")]
        public Nullable<System.DateTime> co_ownerNgayCap { get; set; }

        [StringLength(200)]
        [Display(Name = "Nơi Cấp")]
        public string co_ownerNoiCap { get; set; }

        [StringLength(200)]
        [Display(Name = "Địa chỉ (ĐSH)")]
        public string Co_ownAdress { get; set; }

        [StringLength(200)]
        [Display(Name = "Loại xe máy")]
        public string LoaiXeMay { get; set; }

        [StringLength(200)]
        [Display(Name = "Mẫu sơn")]
        public string MauSon { get; set; }

        [StringLength(200)]
        [Display(Name = "Nhãn hiệu")]
        public string NhanHieu { get; set; }

        [StringLength(200)]
        [Display(Name = "Công Suất")]
        public Nullable<double> CongSuat { get; set; }

        [StringLength(200)]
        [Display(Name = "Nước sản xuất")]
        public string NuocSX { get; set; }

        [StringLength(200)]
        [Display(Name = "Năm sản xuất")]
        public Nullable<int> NamSX { get; set; }

        [StringLength(200)]
        [Display(Name = "Số động cơ")]
        public string SoDongCo { get; set; }

        [StringLength(200)]
        [Display(Name = "Số khung")]
        public string SoKhung { get; set; }

        [StringLength(200)]
        [Display(Name = "Kích thước")]
        public string KichThuoc { get; set; }

        [StringLength(200)]
        [Display(Name = "Trọng lượng")]
        public string TrongLuong { get; set; }

        [StringLength(200)]
        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> CreateDate { get; set; }


        [StringLength(200)]
        [Display(Name = "Ngày cập nhật")]
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
