//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDangKyXeMay.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Spatial;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        public User()
        {
            this.DangKyXeMays = new HashSet<DangKyXeMay>();
        }
     

        public int IDUser { get; set; }

        [Required]
        [StringLength(200)]
        [Display(Name = "Tên người dùng")]
        public string UserName { get; set; }

        [StringLength(200)]
        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }

        [StringLength(200)]
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }

        [StringLength(200)]
        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> DOB { get; set; }

        [StringLength(200)]
        [Display(Name = "CMND")]
        public string CMND { get; set; }

        [StringLength(200)]
        [Display(Name = "Ngày Cấp")]
        public Nullable<System.DateTime> NgayCap { get; set; }

        [StringLength(200)]
        [Display(Name = "Nơi Cấp")]
        public string NoiCap { get; set; }

        [StringLength(200)]
        [Display(Name = "Tên tài khoản")]
        public string accountName { get; set; }

        [StringLength(200)]
        [Display(Name = "Mật khẩu")]
        public string password { get; set; }

        [StringLength(200)]
        [Display(Name = "Loại người dùng")]
        public int Role { get; set; }

        [StringLength(200)]
        [Display(Name = "Giới tính")]
        public bool GioiTinh { get; set; }
    
        public virtual ICollection<DangKyXeMay> DangKyXeMays { get; set; }
    }
}
