//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLaiXe
    {
        public string maBang { get; set; }
        public string hangXe { get; set; }
        public System.DateTime ngayTrungTuyen { get; set; }
        public int ThoiHan { get; set; }
        public int IDUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
