//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyXeMay
    {
        public int ToKhaiDK_ID { get; set; }
        public int registerID { get; set; }
        public string co_ownerName { get; set; }
        public string co_ownerCMND { get; set; }
        public Nullable<System.DateTime> co_ownerNgayCap { get; set; }
        public string co_ownerNoiCap { get; set; }
        public string Co_ownAdress { get; set; }
        public string LoaiXeMay { get; set; }
        public string MauSon { get; set; }
        public string NhanHieu { get; set; }
        public Nullable<double> CongSuat { get; set; }
        public string NuocSX { get; set; }
        public Nullable<int> NamSX { get; set; }
        public string SoDongCo { get; set; }
        public string SoKhung { get; set; }
        public string KichThuoc { get; set; }
        public string TrongLuong { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
