//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLXeMayEntities1 : DbContext
    {
        public QLXeMayEntities1()
            : base("name=QLXeMayEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangLaiXe> BangLaiXes { get; set; }
        public virtual DbSet<DangKyXeMay> DangKyXeMays { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
